### ISSUE TITLE
REAMDE API/examples are out of date

### ISSUE THREAD

**Issue by STguerin** [jason-ash/pyesg#51]
Hey,

Is it possible that the pypi version does not match the repo. The README.md example doesn't work and the installed package (0.1.1) look different.

**Comment by jason-ash** [comment]
Hi @STguerin! The API/syntax in the `README` is outdated, as I was developing functionality and changing things in the code. I'd be happy to update it based on the changes. Are you trying to use the package for anything in particular? I'd love to hear about your use case.

**Comment by STguerin** [comment]
Just doing some saving projection incorporating different asset allocation and was looking around for a decent ESG on python. Offering is small so this project should not have too much competition :P

this is the current install you get from pip install :
<img width="516" alt="foldertree" src="https://user-images.githubusercontent.com/26205925/77863978-2b432100-71f4-11ea-98ad-b6e7eacb7512.PNG">

**Comment by jason-ash** [comment]
It’s been a while since I updated the package on pypi. I’ll push a version with the current code base later today. In the meantime you could clone the git repo locally and install using `pip install .` if you need it right away. Note that this project is still rapidly changing, so if you’re looking for certain functionality, please let me know. Thanks!

**Comment by jason-ash** [comment]
I updated the README and pushed version 0.1.2 to pypi - please let me know if you have any feedback as you use it! Thanks for your interest.
